Added tutorial to optimize the DOS energy reference during training
lab-cosmo/atomistic-cookbook pull request #57
Opened 2024-04-05 15:59 UTC by HowWeiBin

Included a tutorial that shows how to optimize the DOS energy reference during training using Rascaline SOAP power spectrum and pytorch. 

The performance is compared against 2 other models, trained on standard energy references

2024-04-08 13:11 UTC, jwa7 requested changes
Looking good!

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +# 6) Construct Splines for the DOS to facilitate interpolation during model training
It would be useful to use these below for each subsection

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/environment.yml
> +    - metatensor
Not sure if this is needed

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/environment.yml
> +    - rascaline @ git+https://github.com/Luthaf/rascaline@ca957642f512e141c7570e987aadc05c7ac71983
Could use a newer version perhaps?

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +# energy axis, with a grid interval of 0.05 eV
Might be helpful to have this is a variable

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +# and then use cubic interpolation and brentq to determine the fermi level
An explanation of the fact that our truncation range does not include deep states might be nice here, such that we are integrating up to 4 (=/= n_electrons)

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +# For the Average Hartree Potential energy reference
Maybe emphasise that we're generating different datasets: i.e first we align to the Hartree, and we also align to fermi

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +        x, min=spline_positions[0], max=spline_positions[-1] - 0.0005
A comment on why 0.0005 is subtracted here?

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +
```suggestion
# Extract the data tensor from the single block
```

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +        return (x, idx, index)
```suggestion
    return tuple(batch)
```

2024-04-08 13:11 UTC, jwa7 commented on examples/dos-align/dos-align.py
> +        result = torch.exp(result)
A la discussion
```suggestion
```

2024-04-09 12:36 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +        return (x, idx, index)
Somehow it still breaks when i use the tuple(batch) method, will revert back to original

2024-04-09 13:14 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +# 6) Construct Splines for the DOS to facilitate interpolation during model training
Done!

2024-04-09 13:14 UTC, HowWeiBin commented on examples/dos-align/environment.yml
> +    - metatensor
Removed metatensor

2024-04-09 13:14 UTC, HowWeiBin commented on examples/dos-align/environment.yml
> +    - rascaline @ git+https://github.com/Luthaf/rascaline@ca957642f512e141c7570e987aadc05c7ac71983
Stuck to this version for now

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +# energy axis, with a grid interval of 0.05 eV
Done

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +# and then use cubic interpolation and brentq to determine the fermi level
Done

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +# For the Average Hartree Potential energy reference
Done

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +        x, min=spline_positions[0], max=spline_positions[-1] - 0.0005
Done

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +
Done

2024-04-09 13:15 UTC, HowWeiBin commented on examples/dos-align/dos-align.py
> +        result = torch.exp(result)
Done

2024-04-09 15:47 UTC, jwa7 approved these changes
Looks great, thank you!

2024-04-09 16:25 UTC, merged